management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
  metrics:
    enable:
      jvm: false
    distribution:
      percentiles:
        http:
          server:
            requests: 0.01,0.05,0.5,0.9,0.99,1
      percentiles-histogram:
        http:
          server:
            requests: true
      maximum-expected-value:
        http.server.requests: 5s
